server:
  port: 8000

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"
          routes:
            - id: public-user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/signup, /api/v1/users/login, /api/v1/users/token/validate, /api/v1/users/refresh-token
              filters:
                - name: CircuitBreaker
                  args:
                    name: userServiceBreaker
                    fallbackUri: forward:/fallback/users
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - name: JwtAuthenticationFilter
                - name: CircuitBreaker
                  args:
                    name: userServiceBreaker
                    fallbackUri: forward:/fallback/users


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


resilience4j:
  circuitbreaker:
    instances:
      userServiceBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5 # ?? ????? ??? ?? ?? ?  #ringBufferSizeInClosedState ??
        minimumNumberOfCalls: 10 # ?? ?? ??, ? ?? ??? ?? ????? ??? ???
        permittedNumberOfCallsInHalfOpenState: 10 # ?-?? ???? ???? ?? ?  #ringBufferSizeInHalfOpenState ??
        automaticTransitionFromOpenToHalfOpenEnabled: true # ?? ????? ???? ?-?? ??? ????? ??
        waitDurationInOpenState: 5000 # ?? ????? ?? ??? ???? ??
        failureRateThreshold: 50 # ??? ??, ? ??? ???? ??? ???? ?? ????? ????
        eventConsumerBufferSize: 10
        record-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.cloud.gateway.support.NotFoundException
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException

