###쿠폰 정책 생성
POST http://localhost:8005/api/v1/coupon-policies
Content-Type: application/json

{
    "title": "여름 할인 쿠폰",
    "description": "여름 시즌 특별 할인",
    "totalQuantity": 1000,
    "startTime": "2023-07-01T00:00:00",
    "endTime": "2023-07-31T23:59:59",
    "discountType": "FIXED_AMOUNT",
    "discountValue": 5000,
    "minimumOrderAmount": 50000,
    "maximumDiscountAmount": 5000
}

###쿠폰 정책 조회
GET http://localhost:8005/api/v1/coupon-policies/1

###쿠폰 정책 목록 조회
GET http://localhost:8005/api/v1/coupon-policies

###쿠폰 발행
POST localhost:8005/api/v1/coupons/issue
Content-Type: application/json

{
  "couponPolicyId": 1,
  "userId": 100
}

###쿠폰 사용
POST localhost:8005/api/v1/coupons/{id}/use
Content-Type: application/json

{
  "orderId": 1000,
  "orderAmount": 100000
}

###쿠폰 취소
POST http://localhost:8005/api/v1/coupons/1/cancel

###사용자 쿠폰 목록 조회
GET http://localhost:8005/api/v1/coupons/user/1
